### ISSUE TITLE
NuGet Release?

### ISSUE THREAD

**Issue by robertmuehsig** [eVisionSoftware/Harley#10]
Is "Harley.UI" released on NuGet.org? I really like the idea (Cef + OWIN) to build desktop apps and this project seems to be the only one try to combine them nicely.

**Comment by damianh** [comment]
I think I'll get it up on a CI feed first. It needs a bit of baking I
think. Would value your feedback ;)

Got a busy week ahead of me, will try to get to it next weeked. Ping me
personally if I forget.
